const { PERMISSIONS } = require('./business');

const ADMIN_RESERVED_PERMISSIONS = Object.freeze([
  PERMISSIONS.PAYMENT_DISPATCH_READ,
  PERMISSIONS.PAYMENT_DISPATCH_ASSIGN,
  PERMISSIONS.PAYMENT_DISPATCH_CONFIGURE,
  PERMISSIONS.PAYMENT_DISPATCH_CORRECT,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.USERS_PERMISSIONS_MANAGE,
  PERMISSIONS.EMAIL_READ,
  PERMISSIONS.EMAIL_CONTENT_READ,
  PERMISSIONS.EMAIL_PROCESS,
  PERMISSIONS.SYSTEM_LOGS_READ,
  PERMISSIONS.SYSTEM_REFRESH_READ,
  PERMISSIONS.SYSTEM_REFRESH_MANAGE,
  PERMISSIONS.SYSTEM_PROXY_READ,
  PERMISSIONS.SYSTEM_PROXY_MANAGE,
  PERMISSIONS.APPLE_IDS_SECRETS_READ,
  PERMISSIONS.ORDERS_SECRETS_READ,
  PERMISSIONS.RECIPIENTS_EXPORT_SENSITIVE,
]);

const PERMISSION_DEPENDENCIES = Object.freeze({
  [PERMISSIONS.IDENTITY_VERIFY]: [PERMISSIONS.IDENTITY_READ],
  [PERMISSIONS.IDENTITY_BATCH]: [PERMISSIONS.IDENTITY_READ],
  [PERMISSIONS.IDENTITY_EXPORT]: [PERMISSIONS.IDENTITY_READ],
  [PERMISSIONS.ORDERS_EDIT]: [PERMISSIONS.ORDERS_READ],
  [PERMISSIONS.ORDERS_EXPORT]: [PERMISSIONS.ORDERS_READ],
  [PERMISSIONS.ORDERS_REFRESH]: [PERMISSIONS.ORDERS_READ],
  [PERMISSIONS.ORDERS_PAYER_EDIT]: [PERMISSIONS.ORDERS_READ],
  [PERMISSIONS.APPLE_IDS_CREATE]: [PERMISSIONS.APPLE_IDS_READ],
  [PERMISSIONS.APPLE_IDS_EDIT]: [PERMISSIONS.APPLE_IDS_READ],
  [PERMISSIONS.APPLE_IDS_DELETE]: [PERMISSIONS.APPLE_IDS_READ],
  [PERMISSIONS.APPLE_IDS_IMPORT]: [PERMISSIONS.APPLE_IDS_READ, PERMISSIONS.APPLE_IDS_TEMPLATE_READ],
  [PERMISSIONS.RECIPIENTS_CREATE]: [PERMISSIONS.RECIPIENTS_READ],
  [PERMISSIONS.RECIPIENTS_EDIT]: [PERMISSIONS.RECIPIENTS_READ],
  [PERMISSIONS.RECIPIENTS_DELETE]: [PERMISSIONS.RECIPIENTS_READ],
  [PERMISSIONS.RECIPIENTS_EXPORT]: [PERMISSIONS.RECIPIENTS_READ],
  [PERMISSIONS.RECIPIENTS_IMPORT]: [
    PERMISSIONS.RECIPIENTS_READ,
    PERMISSIONS.RECIPIENTS_TEMPLATE_READ,
  ],
  [PERMISSIONS.RECIPIENTS_GENERATE_CONTACT]: [PERMISSIONS.RECIPIENTS_READ],
  [PERMISSIONS.RECIPIENTS_GENERATE_ADDRESS]: [PERMISSIONS.RECIPIENTS_READ],
  [PERMISSIONS.RECIPIENTS_BIND_APPLE_IDS]: [
    PERMISSIONS.RECIPIENTS_READ,
    PERMISSIONS.APPLE_IDS_READ,
  ],
  [PERMISSIONS.CHANNELS_RENAME]: [PERMISSIONS.CHANNELS_READ],
  [PERMISSIONS.PAYMENT_TASKS_HANDLE_OWN]: [PERMISSIONS.PAYMENT_TASKS_READ_OWN],
  [PERMISSIONS.PAYMENT_TASKS_PAYER_EDIT_OWN]: [PERMISSIONS.PAYMENT_TASKS_READ_OWN],
  [PERMISSIONS.PAYMENT_TASKS_LINK_READ_OWN]: [PERMISSIONS.PAYMENT_TASKS_READ_OWN],
  [PERMISSIONS.PAYMENT_TASKS_REFRESH_OWN]: [PERMISSIONS.PAYMENT_TASKS_READ_OWN],
  [PERMISSIONS.PAYMENT_DISPATCH_ASSIGN]: [PERMISSIONS.PAYMENT_DISPATCH_READ],
  [PERMISSIONS.PAYMENT_DISPATCH_CONFIGURE]: [PERMISSIONS.PAYMENT_DISPATCH_READ],
  [PERMISSIONS.PAYMENT_DISPATCH_CORRECT]: [PERMISSIONS.PAYMENT_DISPATCH_READ],
  [PERMISSIONS.USERS_MANAGE]: [PERMISSIONS.USERS_READ],
  [PERMISSIONS.USERS_PERMISSIONS_MANAGE]: [PERMISSIONS.USERS_READ],
  [PERMISSIONS.EMAIL_CONTENT_READ]: [PERMISSIONS.EMAIL_READ],
  [PERMISSIONS.EMAIL_PROCESS]: [PERMISSIONS.EMAIL_READ, PERMISSIONS.EMAIL_CONTENT_READ],
  [PERMISSIONS.SYSTEM_REFRESH_MANAGE]: [PERMISSIONS.SYSTEM_REFRESH_READ],
  [PERMISSIONS.SYSTEM_PROXY_MANAGE]: [PERMISSIONS.SYSTEM_PROXY_READ],
});

/* eslint-disable camelcase -- 权限模块名与对外权限码完全一致 */
const PERMISSION_MODULE_NAMES = Object.freeze({
  identity: '身份核验',
  dashboard: '仪表板',
  stats: '统计',
  orders: '订单',
  apple_ids: 'Apple ID',
  recipients: '取机人',
  channels: '渠道',
  payment_tasks: '付款任务',
  payment_dispatch: '付款调度',
  payers: '付款人',
  users: '用户',
  email: '邮件',
  system: '系统',
});
/* eslint-enable camelcase */

const PERMISSION_LABELS = Object.freeze({
  [PERMISSIONS.IDENTITY_READ]: '查看身份核验原始记录（本人；管理员全部）',
  [PERMISSIONS.IDENTITY_VERIFY]: '单人身份核验',
  [PERMISSIONS.IDENTITY_BATCH]: 'Excel批量身份核验',
  [PERMISSIONS.IDENTITY_EXPORT]: '导出身份核验原始结果',
  [PERMISSIONS.DASHBOARD_READ]: '查看仪表板',
  [PERMISSIONS.STATS_READ]: '查看统计',
  [PERMISSIONS.ORDERS_READ]: '查看全局订单',
  [PERMISSIONS.ORDERS_EDIT]: '编辑普通订单字段',
  [PERMISSIONS.ORDERS_EXPORT]: '导出脱敏订单',
  [PERMISSIONS.ORDERS_REFRESH]: '刷新全局订单',
  [PERMISSIONS.ORDERS_PAYER_EDIT]: '维护全局订单付款人',
  [PERMISSIONS.APPLE_IDS_READ]: '查看 Apple ID',
  [PERMISSIONS.APPLE_IDS_CREATE]: '新增 Apple ID',
  [PERMISSIONS.APPLE_IDS_EDIT]: '编辑 Apple ID',
  [PERMISSIONS.APPLE_IDS_DELETE]: '删除 Apple ID',
  [PERMISSIONS.APPLE_IDS_IMPORT]: '导入 Apple ID',
  [PERMISSIONS.APPLE_IDS_TEMPLATE_READ]: '下载 Apple ID 模板',
  [PERMISSIONS.RECIPIENTS_READ]: '查看取机人',
  [PERMISSIONS.RECIPIENTS_CREATE]: '新增取机人',
  [PERMISSIONS.RECIPIENTS_EDIT]: '编辑取机人',
  [PERMISSIONS.RECIPIENTS_DELETE]: '删除取机人',
  [PERMISSIONS.RECIPIENTS_EXPORT]: '导出脱敏取机人',
  [PERMISSIONS.RECIPIENTS_IMPORT]: '导入取机人',
  [PERMISSIONS.RECIPIENTS_TEMPLATE_READ]: '下载取机人模板',
  [PERMISSIONS.RECIPIENTS_GENERATE_CONTACT]: '生成联系方式',
  [PERMISSIONS.RECIPIENTS_GENERATE_ADDRESS]: '生成地址',
  [PERMISSIONS.RECIPIENTS_BIND_APPLE_IDS]: '绑定 Apple ID',
  [PERMISSIONS.CHANNELS_READ]: '查看渠道',
  [PERMISSIONS.CHANNELS_RENAME]: '修改渠道名称',
  [PERMISSIONS.PAYMENT_TASKS_READ_OWN]: '查看本人付款任务',
  [PERMISSIONS.PAYMENT_TASKS_HANDLE_OWN]: '处理本人付款任务',
  [PERMISSIONS.PAYMENT_TASKS_PAYER_EDIT_OWN]: '维护本人任务付款人',
  [PERMISSIONS.PAYMENT_TASKS_LINK_READ_OWN]: '复制本人任务订单链接',
  [PERMISSIONS.PAYMENT_TASKS_REFRESH_OWN]: '刷新本人任务订单',
  [PERMISSIONS.PAYMENT_DISPATCH_READ]: '查看付款调度',
  [PERMISSIONS.PAYMENT_DISPATCH_ASSIGN]: '分配和转派付款任务',
  [PERMISSIONS.PAYMENT_DISPATCH_CONFIGURE]: '配置付款调度',
  [PERMISSIONS.PAYMENT_DISPATCH_CORRECT]: '纠正付款任务',
  [PERMISSIONS.USERS_READ]: '查看用户',
  [PERMISSIONS.USERS_MANAGE]: '管理用户',
  [PERMISSIONS.USERS_PERMISSIONS_MANAGE]: '分配用户权限',
  [PERMISSIONS.EMAIL_READ]: '查看邮件处理元信息',
  [PERMISSIONS.EMAIL_CONTENT_READ]: '查看完整邮件内容',
  [PERMISSIONS.EMAIL_PROCESS]: '处理邮件',
  [PERMISSIONS.SYSTEM_LOGS_READ]: '查看系统日志',
  [PERMISSIONS.SYSTEM_REFRESH_READ]: '查看刷新运行状态',
  [PERMISSIONS.SYSTEM_REFRESH_MANAGE]: '管理刷新运行状态',
  [PERMISSIONS.SYSTEM_PROXY_READ]: '查看代理状态',
  [PERMISSIONS.SYSTEM_PROXY_MANAGE]: '切换代理',
  [PERMISSIONS.APPLE_IDS_SECRETS_READ]: '查看 Apple ID 敏感字段',
  [PERMISSIONS.ORDERS_SECRETS_READ]: '查看订单敏感字段',
  [PERMISSIONS.RECIPIENTS_EXPORT_SENSITIVE]: '导出取机人敏感字段',
});

const PAYMENT_EXECUTION_PERMISSIONS = Object.freeze([
  PERMISSIONS.PAYMENT_TASKS_READ_OWN,
  PERMISSIONS.PAYMENT_TASKS_HANDLE_OWN,
  PERMISSIONS.PAYMENT_TASKS_PAYER_EDIT_OWN,
  PERMISSIONS.PAYMENT_TASKS_LINK_READ_OWN,
  PERMISSIONS.PAYMENT_TASKS_REFRESH_OWN,
]);

const ALL_PERMISSION_CODES = Object.freeze(Object.values(PERMISSIONS));

/**
 * 返回前端可用的版本化权限目录。
 * @returns {Object[]} 权限目录
 */
function getPermissionCatalog() {
  const reserved = new Set(ADMIN_RESERVED_PERMISSIONS);
  return ALL_PERMISSION_CODES.map(code => ({
    code,
    label: PERMISSION_LABELS[code],
    module: code.split('.')[0],
    moduleLabel: PERMISSION_MODULE_NAMES[code.split('.')[0]] || '系统',
    dependencies: PERMISSION_DEPENDENCIES[code] || [],
    adminReserved: reserved.has(code),
  }));
}

module.exports = {
  ADMIN_RESERVED_PERMISSIONS,
  PERMISSION_DEPENDENCIES,
  PAYMENT_EXECUTION_PERMISSIONS,
  ALL_PERMISSION_CODES,
  getPermissionCatalog,
};
