export const PERMISSIONS = Object.freeze({
  IDENTITY_READ: 'identity.read',
  IDENTITY_VERIFY: 'identity.verify',
  IDENTITY_BATCH: 'identity.batch',
  IDENTITY_EXPORT: 'identity.export',
  DASHBOARD_READ: 'dashboard.read',
  STATS_READ: 'stats.read',
  ORDERS_READ: 'orders.read',
  ORDERS_EDIT: 'orders.edit',
  ORDERS_EXPORT: 'orders.export',
  ORDERS_REFRESH: 'orders.refresh',
  ORDERS_PAYER_EDIT: 'orders.payer.edit',
  APPLE_IDS_READ: 'apple_ids.read',
  APPLE_IDS_CREATE: 'apple_ids.create',
  APPLE_IDS_EDIT: 'apple_ids.edit',
  APPLE_IDS_DELETE: 'apple_ids.delete',
  APPLE_IDS_IMPORT: 'apple_ids.import',
  APPLE_IDS_TEMPLATE_READ: 'apple_ids.template.read',
  RECIPIENTS_READ: 'recipients.read',
  RECIPIENTS_CREATE: 'recipients.create',
  RECIPIENTS_EDIT: 'recipients.edit',
  RECIPIENTS_DELETE: 'recipients.delete',
  RECIPIENTS_EXPORT: 'recipients.export',
  RECIPIENTS_IMPORT: 'recipients.import',
  RECIPIENTS_TEMPLATE_READ: 'recipients.template.read',
  RECIPIENTS_GENERATE_CONTACT: 'recipients.generate_contact',
  RECIPIENTS_GENERATE_ADDRESS: 'recipients.generate_address',
  RECIPIENTS_BIND_APPLE_IDS: 'recipients.bind_apple_ids',
  CHANNELS_READ: 'channels.read',
  CHANNELS_RENAME: 'channels.rename',
  PAYMENT_TASKS_READ_OWN: 'payment_tasks.read_own',
  PAYMENT_TASKS_HANDLE_OWN: 'payment_tasks.handle_own',
  PAYMENT_TASKS_PAYER_EDIT_OWN: 'payment_tasks.payer.edit_own',
  PAYMENT_TASKS_LINK_READ_OWN: 'payment_tasks.link.read_own',
  PAYMENT_TASKS_REFRESH_OWN: 'payment_tasks.refresh_own',
  PAYMENT_DISPATCH_READ: 'payment_dispatch.read',
  PAYMENT_DISPATCH_ASSIGN: 'payment_dispatch.assign',
  PAYMENT_DISPATCH_CONFIGURE: 'payment_dispatch.configure',
  PAYMENT_DISPATCH_CORRECT: 'payment_dispatch.correct',
  USERS_READ: 'users.read',
  USERS_MANAGE: 'users.manage',
  USERS_PERMISSIONS_MANAGE: 'users.permissions.manage',
  EMAIL_READ: 'email.read',
  EMAIL_CONTENT_READ: 'email.content.read',
  EMAIL_PROCESS: 'email.process',
  SYSTEM_LOGS_READ: 'system.logs.read',
});

export const PAYMENT_EXECUTION_PERMISSIONS = Object.freeze([
  PERMISSIONS.PAYMENT_TASKS_READ_OWN,
  PERMISSIONS.PAYMENT_TASKS_HANDLE_OWN,
  PERMISSIONS.PAYMENT_TASKS_PAYER_EDIT_OWN,
  PERMISSIONS.PAYMENT_TASKS_LINK_READ_OWN,
  PERMISSIONS.PAYMENT_TASKS_REFRESH_OWN,
]);
