/**
 * 表格列配置常量
 * 定义 Orders、AppleIds、Recipients 三个表格的可配置列
 */

export const ordersColumns = [
  // 基础信息
  {
    key: 'orderNumber',
    label: '订单号',
    width: '140px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'status',
    label: '订单状态',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'validationStatus',
    label: '校验状态',
    width: '120px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  // Apple ID 相关
  {
    key: 'appleId',
    label: 'Apple ID',
    width: '200px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'applePassword',
    label: 'Apple 密码',
    width: '120px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
    sensitive: true,
  },
  // 收件人相关
  {
    key: 'recipientName',
    label: '取机人',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'recipientIdCard',
    label: '身份证号',
    width: '180px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
    sensitive: true,
  },
  {
    key: 'recipientEmail',
    label: '收件人邮箱',
    width: '200px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'recipientPhone',
    label: '联系电话',
    width: '140px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'recipientAddress',
    label: '收件地址',
    width: '250px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  // 产品信息
  {
    key: 'products',
    label: '商品',
    width: '300px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  // 订单信息
  {
    key: 'orderUrl',
    label: '订单链接',
    width: '100px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'orderDate',
    label: '下单时间',
    width: '160px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  // 取货信息
  {
    key: 'pickupStore',
    label: '取货门店',
    width: '180px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'pickupStoreCode',
    label: '门店代码',
    width: '100px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'pickupCode',
    label: '取货码',
    width: '120px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'pickupTimeSlot',
    label: '取货时间段',
    width: '140px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'actualPickupDate',
    label: '实际取货日期',
    width: '140px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  // 付款信息
  {
    key: 'paymentMethod',
    label: '付款方式',
    width: '120px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'payerName',
    label: '付款人',
    width: '100px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  // 爬虫相关
  {
    key: 'lastCrawledAt',
    label: '最后爬取时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  {
    key: 'crawlFailCount',
    label: '爬取失败次数',
    width: '120px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  // 业务字段
  {
    key: 'tag',
    label: '标签',
    width: '150px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'notes',
    label: '备注',
    width: '200px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  // 时间戳
  {
    key: 'createdAt',
    label: '创建时间',
    width: '160px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'updatedAt',
    label: '更新时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  // 操作
  {
    key: 'actions',
    label: '操作',
    width: '80px',
    defaultVisible: true,
    sortable: false,
    pinned: true,
  },
]

export const appleIdsColumns = [
  // 基础信息
  {
    key: 'appleId',
    label: 'Apple ID',
    width: '250px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'password',
    label: '密码',
    width: '150px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'nickname',
    label: '备注名称',
    width: '150px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  // 安全信息
  {
    key: 'securityQa',
    label: '密保问答',
    width: '300px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  // 账号属性
  {
    key: 'country',
    label: '国家地区',
    width: '120px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'isModified',
    label: '已修改',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'status',
    label: '状态',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  // 统计信息
  {
    key: 'orderCount',
    label: '订单数',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'lastOrderDate',
    label: '最后下单',
    width: '160px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  // 时间戳
  {
    key: 'createdAt',
    label: '创建时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  {
    key: 'updatedAt',
    label: '更新时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  // 操作
  {
    key: 'actions',
    label: '操作',
    width: '100px',
    defaultVisible: true,
    sortable: false,
    pinned: true,
  },
]

export const recipientsColumns = [
  {
    key: 'name',
    label: '姓名',
    width: '120px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'idCard',
    label: '身份证号',
    width: '180px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'phone',
    label: '联系电话',
    width: '140px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'email',
    label: '下单邮箱',
    width: '200px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'address',
    label: '地址',
    width: '250px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'boundAppleId',
    label: '绑定 Apple ID',
    width: '200px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  {
    key: 'tag',
    label: '标签',
    width: '120px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'status',
    label: '状态',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'orderCount',
    label: '订单数',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'createdAt',
    label: '创建时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  {
    key: 'actions',
    label: '操作',
    width: '100px',
    defaultVisible: true,
    sortable: false,
    pinned: true,
  },
]
