/**
 * 表格列配置常量
 * 定义 Orders、AppleIds、Recipients 三个表格的可配置列
 */

export const ordersColumns = [
  {
    key: 'orderNumber',
    label: '订单号',
    width: '140px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'serialNumbers',
    label: 'Serial No.',
    width: '160px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'emailOrderStatus',
    label: '订单状态',
    width: '120px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'emailLifecycleUpdatedAt',
    label: '邮件状态更新时间',
    width: '180px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'products',
    label: '商品',
    width: '300px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'recipientName',
    label: '取机人',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'recipientTag',
    label: 'TAG',
    width: '140px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'orderDate',
    label: '下单时间',
    width: '160px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'emailPickupInfo',
    label: '取货信息',
    width: '240px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'paymentMethod',
    label: '付款方式',
    width: '120px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'createdAt',
    label: '创建时间',
    width: '160px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'applePassword',
    label: 'Apple 密码',
    width: '120px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
    sensitive: true,
  },
  {
    key: 'recipientIdCard',
    label: '身份证号',
    width: '180px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
    sensitive: true,
  },
  {
    key: 'recipientEmail',
    label: '收件人邮箱',
    width: '200px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'recipientAddress',
    label: '收件地址',
    width: '250px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'orderUrl',
    label: '订单链接',
    width: '100px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'payerName',
    label: '付款人',
    width: '100px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'tag',
    label: '授权 TAG',
    width: '150px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'notes',
    label: '备注',
    width: '200px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'updatedAt',
    label: '更新时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  {
    key: 'actions',
    label: '操作',
    width: '300px',
    defaultVisible: true,
    sortable: false,
    pinned: true,
  },
];

export const appleIdsColumns = [
  // 基础信息
  {
    key: 'appleId',
    label: 'Apple ID',
    width: '250px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'password',
    label: '密码',
    width: '150px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'notes',
    label: '备注',
    width: '150px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  // 安全信息
  {
    key: 'securityQa',
    label: '密保问答',
    width: '300px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  // 账号属性
  {
    key: 'status',
    label: '状态',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'bound',
    label: '当前绑定',
    defaultVisible: true,
    sortable: false,
    width: '160px',
    pinned: false,
  },
  {
    key: 'country',
    label: '国家地区',
    width: '120px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  // 统计信息
  {
    key: 'orderCount',
    label: '订单数',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'lastOrderDate',
    label: '最后下单',
    width: '160px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  // 时间戳
  {
    key: 'createdAt',
    label: '创建时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  {
    key: 'updatedAt',
    label: '更新时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  // 操作
  {
    key: 'actions',
    label: '操作',
    width: '100px',
    defaultVisible: true,
    sortable: false,
    pinned: true,
  },
];

export const recipientsColumns = [
  {
    key: 'name',
    label: '姓名',
    width: '120px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'idCard',
    label: '身份证号',
    width: '180px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'tag',
    label: 'TAG',
    width: '160px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'channel',
    label: '渠道',
    width: '140px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'boundAppleId',
    label: '绑定 Apple ID',
    width: '240px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'realPhone',
    label: '真实联系电话',
    width: '160px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'status',
    label: '状态',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'orderCount',
    label: '订单数',
    width: '100px',
    defaultVisible: true,
    sortable: true,
    pinned: false,
  },
  {
    key: 'notes',
    label: '备注',
    defaultVisible: true,
    sortable: false,
    width: '180px',
  },
  {
    key: 'phone',
    label: '下单手机号',
    width: '140px',
    defaultVisible: true,
    sortable: false,
    pinned: false,
  },
  {
    key: 'email',
    label: '下单邮箱',
    width: '200px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'address',
    label: '地址',
    width: '250px',
    defaultVisible: false,
    sortable: false,
    pinned: false,
  },
  {
    key: 'password',
    label: '关联账号密码',
    defaultVisible: false,
    sortable: false,
    width: '160px',
    sensitive: true,
  },
  {
    key: 'bound',
    label: '当前绑定',
    defaultVisible: false,
    sortable: false,
    width: '160px',
  },
  {
    key: 'createdAt',
    label: '创建时间',
    width: '160px',
    defaultVisible: false,
    sortable: true,
    pinned: false,
  },
  {
    key: 'actions',
    label: '操作',
    width: '100px',
    defaultVisible: true,
    sortable: false,
    pinned: true,
  },
];
